### ISSUE TITLE
Clarify the behavior of `LAST(*)` (and other wildcard selectors)

### ISSUE THREAD

**Issue by jsternberg** [influxdata/docs.influxdata.com#1095]
###### URL for relevant page?
https://github.com/influxdata/influxdb/issues/8280#issuecomment-293020558

###### What products and version are you using?
InfluxDB 1.2.2

There's a reasonable confusion about using wildcards inside of selectors. It's expected that it will find the first or last time, but our database doesn't keep fields together by row, but by column. So in order to find a specific time, you need to select a specific field. Since `LAST(*)` hides that it is expanded to become `LAST(field1), LAST(field2)`, there is an expectation that `LAST(*)` has the same behavior as a selector, but it commonly has the behavior of an aggregator.

Inside of the documentation for wildcards, we should likely include a note that using `LAST(*)` will likely not give them the timestamp they are looking for. It's possible it will, but only in the situation that `*` expands to exactly one field.

**Comment by rkuchan** [comment]
Thanks, @jsternberg! I'm actually in the process of heavily revising the functions doc now and will include this in there:  https://github.com/influxdata/docs.influxdata.com/pull/1092

**Comment by rkuchan** [comment]
Fixed in https://github.com/influxdata/docs.influxdata.com/pull/1092/commits/911eb7c306ae8f6a2bffce15de3938f4044254de

**Comment by andig** [comment]
@rkuchan could you check https://github.com/influxdata/influxdb/issues/11902? Seems this is still not fixed.
